# Generated by Django 6.0.8 on 2026-09-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, help_text='Optional location', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='tagged',
            field=models.CharField(blank=True, help_text='Comma @usernames', max_length=200),
        ),
    ]
