# Generated by Django 6.0.8 on 2026-09-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, help_text='Comma-separated e.g. Tech,Music', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_done',
            field=models.BooleanField(default=False),
        ),
    ]
